$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

experiment_name: cli-v2-pipelines-demo
display_name: pipeline with components
description: Pipeline with 2 component jobs with data dependencies

settings:
  default_compute: azureml:cpu-cluster

outputs:
  final_pipeline_output:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/pipeline_output/cats
    mode: rw_mount

jobs:

  rotate:
    type: command
    #component: azureml:rotate_images:1
    component: file:../components/rotate_img/definition.yml
    inputs:
      image_folder:
        type: uri_folder
        path: wasbs://data@azuremlexampledata.blob.core.windows.net/pet-images/cat # ./testsampledata
        mode: ro_mount
      degrees: 180
    outputs:
      output_folder:
        mode: rw_mount
      
  compress:
    type: command
    component: file:../components/compress_img/definition.yml
    inputs:
      image_folder: ${{parent.jobs.rotate.outputs.output_folder}}
      new_size_ratio: 0.5
    outputs:
      output_folder: ${{parent.outputs.final_pipeline_output}}
